import java.io.*;
import java.net.*;
import java.util.*;

public class Client {

    public static void main(String[] args) throws IOException {
        Socket clientSoc = null;
        Scanner clientinput = null;
        Scanner fromServer = null;
        PrintWriter pr = null;
        String input = null;

        System.out.println("Client Started ...");

        try {
            clientSoc = new Socket("localhost", 5656);
            fromServer = new Scanner(clientSoc.getInputStream());
            clientinput = new Scanner(System.in);
            pr = new PrintWriter(clientSoc.getOutputStream(), true);

            do {
                if (fromServer.hasNextLine()) {
                    String serverResponse = fromServer.nextLine();
                    System.out.println(serverResponse);

                    if (serverResponse.equals("You have successfully logged in. Here is the secured menu:")) {
                        // Read the menu options until "END_MENU" marker is received
                        StringBuilder menuBuilder = new StringBuilder();
                        String menuOption;
                        while (fromServer.hasNextLine() && !(menuOption = fromServer.nextLine()).equals("END_MENU")) {
                            menuBuilder.append(menuOption).append("\n");
                        }
                        System.out.println(menuBuilder.toString().trim()); // Display the complete menu
                    } else if (serverResponse.equals("Please supply your Registered PhoneNumber And MemberNumber")) {
                        System.out.println("Please Enter your MemberNumer :");
                        input = clientinput.nextLine();
                        pr.println(input);
                        System.out.println("Please Enter your phoneNumber :");
                        int d = clientinput.nextInt();
                        pr.println(d);
                        System.out.println(fromServer.nextLine());
                    } else if (serverResponse.equals("Enter the member ID:")) {
                        input = clientinput.nextLine();
                        pr.println(input);
                    } else if (serverResponse.equals("Enter 'CheckStatement' to generate statement:")) {
                        pr.println("CheckStatement"); // Send the CheckStatement command to the server
                        System.out.println("Enter the date from (YYYY-MM-DD): ");
                        input = clientinput.nextLine();
                        pr.println(input);
                        System.out.println("Enter the date to (YYYY-MM-DD): ");
                        input = clientinput.nextLine();
                        pr.println(input);

                        // Wait for the calculations and statement generated by the server
                        double loanProgress = Double.parseDouble(fromServer.nextLine());
                        double contributionProgress = Double.parseDouble(fromServer.nextLine());
                        double saccoPerformance = Double.parseDouble(fromServer.nextLine());

                        System.out.println("Percentage loan progress: " + loanProgress + "%");
                        System.out.println("Percentage contribution progress: " + contributionProgress + "%");
                        System.out.println("Sacco performance: " + saccoPerformance + "%");

                        // Receive the statement from the server
                        boolean statementGenerated = Boolean.parseBoolean(fromServer.nextLine());
                        if (statementGenerated) {
                            String statement = fromServer.nextLine();
                            System.out.println("Statement:\n" + statement);
                        } else {
                            System.out.println("Failed to generate the statement. Please try again.");
                        }
                    }
                }

                input = clientinput.nextLine();
                pr.println(input);

            } while (!input.equalsIgnoreCase("logout"));

        } catch (IOException e) {
            System.out.println("Error:" + e.getMessage());
        }
    }
}
